### List all messages
GET http://localhost:3000/messages
### Create a new message
POST http://localhost:3000/messages HTTP/1.1
content-type: : application/json

{
    "content":"Hi there"
}
### Get message
GET http://localhost:3000/messages/1
